language: java
jdk: oraclejdk15

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search

env:
  - CODECOV_TOKEN="b024e689-71b2-4617-8328-dfa1d5efb0b4"