package com.jamex.refereestaffer.model.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ConfigName {
    HARDNESS_LEVEL_MULTIPLIER,
    HARDNESS_LEVEL_INCREMENTER,
    HARDNESS_LEVEL_SAME_CITY_INCREMENTER,
    HARDNESS_LEVEL_MATCH_ON_TOP_INCREMENTER,
    HARDNESS_LEVEL_MATCH_ON_BOTTOM_INCREMENTER,
    NUMBER_OF_EDGE_TEAMS,
    AVERAGE_GRADE_MULTIPLIER,
    EXPERIENCE_MULTIPLIER,
    NUMBER_OF_MATCHES_MULTIPLIER,
    HOME_TEAM_REFEREED_MULTIPLIER,
    AWAY_TEAM_REFEREED_MULTIPLIER
}
