spring:
  datasource:
    url: jdbc:h2:file:./data/db/RefereeStaffer
  sql:
    init:
      mode: always
  # TODO change data.sql to not insert data when data exists and remove below property
  jpa:
    hibernate:
      ddl-auto: create-drop