spring:
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    operationsSorter: method