spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;NON_KEYWORDS=VALUE
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    operationsSorter: method