INSERT INTO config (id, name, value)
VALUES (1, 'AVERAGE_GRADE_MULTIPLIER', 50.0),
       (2, 'EXPERIENCE_MULTIPLIER', 0.01),
       (3, 'NUMBER_OF_MATCHES_MULTIPLIER', 3.0),
       (4, 'HOME_TEAM_REFEREED_MULTIPLIER', 1.3),
       (5, 'AWAY_TEAM_REFEREED_MULTIPLIER', 1.3),
       (6, 'DIFFICULTY_LEVEL_MULTIPLIER', 1.0),
       (7, 'DIFFICULTY_LEVEL_SAME_CITY_INCREMENTER', 10.0),
       (8, 'DIFFICULTY_LEVEL_MATCH_ON_TOP_INCREMENTER', 7.0),
       (9, 'DIFFICULTY_LEVEL_MATCH_ON_BOTTOM_INCREMENTER', 5.0),
       (10, 'NUMBER_OF_EDGE_TEAMS', 3.0),
       (11, 'DIFFICULTY_LEVEL_INCREMENTER', 100.0);
