# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.0.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: |
        cd src/main/webapp
        npm ci
    - name: npm run build --if-present
      run: |
        cd src/main/webapp
        npm run build --if-present
    - name: npm test
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev
        cd src/main/webapp
        npm test
